TASK: "HandGestureRecognition"
DATASET:
  ROOT_PATH: "/data2/zhangziwei/datasets/HGR-dataset/version6"
  NUM_CLASSES: 15
  TRAIN_MODE: "train"
  SAMPLER: "Random"
  FUNC: "CustomDataset"
  AUGMENTATION:
    NAME: ""
    AUTO: False

MODEL:
  NAME: "resnet18"
  PRETRAINED: True

  HEAD:
    NAME: ["BasicHead"]
    MODE: "small"
    DROPOUT: 0.2

INPUT:
  SIZE: (256, 256)

SOLVER:
  OPTIMIZER:
    NAME: "AdaBelief"
    LR_START: 5e-3
  LOSS:
    NAME: ["CrossEntropyLoss"]
  ACCUMULATE_STEPS: 1

MAX_EPOCH: 50
NUM_WORKERS: 16
BATCH_SIZE: 256
DATE: "2021-09-24"
EXTRA: ""
KFOLD: True
