from .config import CfgNode as CN


_C = CN()

_C.MAX_EPOCH = 20
_C.NUM_WORKERS = 16
_C.BATCH_SIZE = 64
_C.DEVICE = 'cuda'
# OUTPUT
_C.OUTPUT_NAME = ''
_C.EXTRA = ''
# TASK
_C.TASK = 'TEST'
_C.DATE = ''

# dataset
_C.DATASET = CN()
_C.DATASET.TRAIN_MODE = 'train'
_C.DATASET.NUM_CLASSES = 5
_C.DATASET.ROOT_PATH = ''
_C.DATASET.AUGMENTATION = CN()
_C.DATASET.AUGMENTATION.NAME = ''
_C.DATASET.FUNC = 'CustomDataset'


# model
_C.MODEL = CN()
_C.MODEL.NAME = ''
_C.MODEL.WEIGHTS = None
_C.MODEL.PRETRAINED = True


# METRIC
_C.MODEL.METRIC = CN()
_C.MODEL.METRIC.NAME = None

# HEAD
_C.MODEL.HEAD = CN()
_C.MODEL.HEAD.NAME = 'MultiHead'

# INPUT
_C.INPUT = CN()
_C.INPUT.SIZE = (360, 240)

# SOLVER
_C.SOLVER = CN()
_C.SOLVER.OPTIMIZER = CN()
_C.SOLVER.OPTIMIZER.NAME = 'RAdam'
_C.SOLVER.OPTIMIZER.LR_START = 2e-3

# LOSS
_C.SOLVER.LOSS = CN()
_C.SOLVER.LOSS.NAME = 'CrossEntropyLoss'

_C.SOLVER.ACCUMULATE_STEPS = 1
